//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1026
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JHDock.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JHDock.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap CA登录常态 {
            get {
                object obj = ResourceManager.GetObject("CA登录常态", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CA登录点击态 {
            get {
                object obj = ResourceManager.GetObject("CA登录点击态", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CZEYY_LOGO {
            get {
                object obj = ResourceManager.GetObject("CZEYY_LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EMR {
            get {
                object obj = ResourceManager.GetObject("EMR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HTRMYY {
            get {
                object obj = ResourceManager.GetObject("HTRMYY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JHIP_LOGO {
            get {
                object obj = ResourceManager.GetObject("JHIP_LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JMEYY_LOGO {
            get {
                object obj = ResourceManager.GetObject("JMEYY_LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JMEYY_LOGO1 {
            get {
                object obj = ResourceManager.GetObject("JMEYY_LOGO1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap QHRMYY_LOGO {
            get {
                object obj = ResourceManager.GetObject("QHRMYY_LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon sso图标 {
            get {
                object obj = ResourceManager.GetObject("sso图标", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap user1 {
            get {
                object obj = ResourceManager.GetObject("user1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap user1触发 {
            get {
                object obj = ResourceManager.GetObject("user1触发", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 三角指向_左 {
            get {
                object obj = ResourceManager.GetObject("三角指向_左", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 个人信息常态 {
            get {
                object obj = ResourceManager.GetObject("个人信息常态", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 产品logo {
            get {
                object obj = ResourceManager.GetObject("产品logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 人员信息 {
            get {
                object obj = ResourceManager.GetObject("人员信息", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 人员信息_咸阳 {
            get {
                object obj = ResourceManager.GetObject("人员信息_咸阳", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 修改密码 {
            get {
                object obj = ResourceManager.GetObject("修改密码", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 修改密码常态 {
            get {
                object obj = ResourceManager.GetObject("修改密码常态", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 修改密码点击态 {
            get {
                object obj = ResourceManager.GetObject("修改密码点击态", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 关闭 {
            get {
                object obj = ResourceManager.GetObject("关闭", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 关闭_咸阳 {
            get {
                object obj = ResourceManager.GetObject("关闭_咸阳", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 关闭常态 {
            get {
                object obj = ResourceManager.GetObject("关闭常态", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 关闭按钮 {
            get {
                object obj = ResourceManager.GetObject("关闭按钮", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 关闭点击态 {
            get {
                object obj = ResourceManager.GetObject("关闭点击态", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 医院院徽 {
            get {
                object obj = ResourceManager.GetObject("医院院徽", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 医院院徽1 {
            get {
                object obj = ResourceManager.GetObject("医院院徽1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 单点关闭常态 {
            get {
                object obj = ResourceManager.GetObject("单点关闭常态", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 单点关闭点击态 {
            get {
                object obj = ResourceManager.GetObject("单点关闭点击态", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 取消常态 {
            get {
                object obj = ResourceManager.GetObject("取消常态", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 取消点击态 {
            get {
                object obj = ResourceManager.GetObject("取消点击态", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 取消触发 {
            get {
                object obj = ResourceManager.GetObject("取消触发", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 取消默认 {
            get {
                object obj = ResourceManager.GetObject("取消默认", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 嘉和信息logo {
            get {
                object obj = ResourceManager.GetObject("嘉和信息logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 图标列表的窗体背景1 {
            get {
                object obj = ResourceManager.GetObject("图标列表的窗体背景1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 图标列表的窗体背景2 {
            get {
                object obj = ResourceManager.GetObject("图标列表的窗体背景2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 图标列表的窗体背景3 {
            get {
                object obj = ResourceManager.GetObject("图标列表的窗体背景3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 图标列表的窗体背景4 {
            get {
                object obj = ResourceManager.GetObject("图标列表的窗体背景4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 图标列表的窗体背景5 {
            get {
                object obj = ResourceManager.GetObject("图标列表的窗体背景5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 图标列表的窗体背景6 {
            get {
                object obj = ResourceManager.GetObject("图标列表的窗体背景6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 图标列表的窗体背景7 {
            get {
                object obj = ResourceManager.GetObject("图标列表的窗体背景7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 图标列表的窗体背景8 {
            get {
                object obj = ResourceManager.GetObject("图标列表的窗体背景8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 图标列表的窗体背景9 {
            get {
                object obj = ResourceManager.GetObject("图标列表的窗体背景9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 小背景 {
            get {
                object obj = ResourceManager.GetObject("小背景", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 底图 {
            get {
                object obj = ResourceManager.GetObject("底图", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 弹窗关闭 {
            get {
                object obj = ResourceManager.GetObject("弹窗关闭", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 文字部分 {
            get {
                object obj = ResourceManager.GetObject("文字部分", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 最小化 {
            get {
                object obj = ResourceManager.GetObject("最小化", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 最小化常态 {
            get {
                object obj = ResourceManager.GetObject("最小化常态", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 最小化点击态 {
            get {
                object obj = ResourceManager.GetObject("最小化点击态", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 框中 {
            get {
                object obj = ResourceManager.GetObject("框中", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 框右__左 {
            get {
                object obj = ResourceManager.GetObject("框右__左", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 框左__左 {
            get {
                object obj = ResourceManager.GetObject("框左__左", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 登录常态 {
            get {
                object obj = ResourceManager.GetObject("登录常态", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 登录点击态 {
            get {
                object obj = ResourceManager.GetObject("登录点击态", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 登录界面 {
            get {
                object obj = ResourceManager.GetObject("登录界面", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 确定触发 {
            get {
                object obj = ResourceManager.GetObject("确定触发", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 确定默认 {
            get {
                object obj = ResourceManager.GetObject("确定默认", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 翻页键hover3 {
            get {
                object obj = ResourceManager.GetObject("翻页键hover3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 翻页键hover4 {
            get {
                object obj = ResourceManager.GetObject("翻页键hover4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 背景图 {
            get {
                object obj = ResourceManager.GetObject("背景图", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 背景图2 {
            get {
                object obj = ResourceManager.GetObject("背景图2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 输入框触发 {
            get {
                object obj = ResourceManager.GetObject("输入框触发", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 输入框默认 {
            get {
                object obj = ResourceManager.GetObject("输入框默认", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 输入框默认_2 {
            get {
                object obj = ResourceManager.GetObject("输入框默认_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 锁2 {
            get {
                object obj = ResourceManager.GetObject("锁2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 锁2触发 {
            get {
                object obj = ResourceManager.GetObject("锁2触发", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 锁定图标划过状态 {
            get {
                object obj = ResourceManager.GetObject("锁定图标划过状态", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 锁定图标常态状态 {
            get {
                object obj = ResourceManager.GetObject("锁定图标常态状态", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 锁定图标点击状态 {
            get {
                object obj = ResourceManager.GetObject("锁定图标点击状态", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 问号 {
            get {
                object obj = ResourceManager.GetObject("问号", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 问号划过 {
            get {
                object obj = ResourceManager.GetObject("问号划过", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 隐藏单点菜单 {
            get {
                object obj = ResourceManager.GetObject("隐藏单点菜单", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 隐藏常态 {
            get {
                object obj = ResourceManager.GetObject("隐藏常态", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 隐藏点击态 {
            get {
                object obj = ResourceManager.GetObject("隐藏点击态", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
