//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1026
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JHDock.JHIPSSO {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://jhipwebsvc.bjgoodwill.com/", ConfigurationName="JHIPSSO.SsoWebsvc")]
    public interface SsoWebsvc {
        
        // CODEGEN: 命名空间  的元素名称 inputPara 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JHDock.JHIPSSO.LoadAllSystemResponse LoadAllSystem(JHDock.JHIPSSO.LoadAllSystem request);
        
        // CODEGEN: 命名空间  的元素名称 inputPara 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JHDock.JHIPSSO.LoadSystemFileResponse LoadSystemFile(JHDock.JHIPSSO.LoadSystemFile request);
        
        // CODEGEN: 命名空间  的元素名称 inputPara 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JHDock.JHIPSSO.LogInResponse LogIn(JHDock.JHIPSSO.LogIn request);
        
        // CODEGEN: 命名空间  的元素名称 inputPara 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JHDock.JHIPSSO.CAlLoginResponse CAlLogin(JHDock.JHIPSSO.CAlLogin request);
        
        // CODEGEN: 命名空间  的元素名称 inputPara 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JHDock.JHIPSSO.getUserDetailInfoResponse getUserDetailInfo(JHDock.JHIPSSO.getUserDetailInfo request);
        
        // CODEGEN: 命名空间  的元素名称 inputPara 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JHDock.JHIPSSO.getNewSessionIDResponse getNewSessionID(JHDock.JHIPSSO.getNewSessionID request);
        
        // CODEGEN: 命名空间  的元素名称 inputPara 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JHDock.JHIPSSO.ModifyPasswordResponse ModifyPassword(JHDock.JHIPSSO.ModifyPassword request);
        
        // CODEGEN: 命名空间  的元素名称 inputPara 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JHDock.JHIPSSO.LoadSystemDetailResponse LoadSystemDetail(JHDock.JHIPSSO.LoadSystemDetail request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadAllSystem {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadAllSystem", Namespace="http://jhipwebsvc.bjgoodwill.com/", Order=0)]
        public JHDock.JHIPSSO.LoadAllSystemBody Body;
        
        public LoadAllSystem() {
        }
        
        public LoadAllSystem(JHDock.JHIPSSO.LoadAllSystemBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class LoadAllSystemBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string inputPara;
        
        public LoadAllSystemBody() {
        }
        
        public LoadAllSystemBody(string inputPara) {
            this.inputPara = inputPara;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadAllSystemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadAllSystemResponse", Namespace="http://jhipwebsvc.bjgoodwill.com/", Order=0)]
        public JHDock.JHIPSSO.LoadAllSystemResponseBody Body;
        
        public LoadAllSystemResponse() {
        }
        
        public LoadAllSystemResponse(JHDock.JHIPSSO.LoadAllSystemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://jhipwebsvc.bjgoodwill.com/")]
    public partial class LoadAllSystemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string returnVal;
        
        public LoadAllSystemResponseBody() {
        }
        
        public LoadAllSystemResponseBody(string returnVal) {
            this.returnVal = returnVal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadSystemFile {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadSystemFile", Namespace="http://jhipwebsvc.bjgoodwill.com/", Order=0)]
        public JHDock.JHIPSSO.LoadSystemFileBody Body;
        
        public LoadSystemFile() {
        }
        
        public LoadSystemFile(JHDock.JHIPSSO.LoadSystemFileBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class LoadSystemFileBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string inputPara;
        
        public LoadSystemFileBody() {
        }
        
        public LoadSystemFileBody(string inputPara) {
            this.inputPara = inputPara;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadSystemFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadSystemFileResponse", Namespace="http://jhipwebsvc.bjgoodwill.com/", Order=0)]
        public JHDock.JHIPSSO.LoadSystemFileResponseBody Body;
        
        public LoadSystemFileResponse() {
        }
        
        public LoadSystemFileResponse(JHDock.JHIPSSO.LoadSystemFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://jhipwebsvc.bjgoodwill.com/")]
    public partial class LoadSystemFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string returnVal;
        
        public LoadSystemFileResponseBody() {
        }
        
        public LoadSystemFileResponseBody(string returnVal) {
            this.returnVal = returnVal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogIn {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogIn", Namespace="http://jhipwebsvc.bjgoodwill.com/", Order=0)]
        public JHDock.JHIPSSO.LogInBody Body;
        
        public LogIn() {
        }
        
        public LogIn(JHDock.JHIPSSO.LogInBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class LogInBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string inputPara;
        
        public LogInBody() {
        }
        
        public LogInBody(string inputPara) {
            this.inputPara = inputPara;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogInResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogInResponse", Namespace="http://jhipwebsvc.bjgoodwill.com/", Order=0)]
        public JHDock.JHIPSSO.LogInResponseBody Body;
        
        public LogInResponse() {
        }
        
        public LogInResponse(JHDock.JHIPSSO.LogInResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://jhipwebsvc.bjgoodwill.com/")]
    public partial class LogInResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string returnVal;
        
        public LogInResponseBody() {
        }
        
        public LogInResponseBody(string returnVal) {
            this.returnVal = returnVal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CAlLogin {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CAlLogin", Namespace="http://jhipwebsvc.bjgoodwill.com/", Order=0)]
        public JHDock.JHIPSSO.CAlLoginBody Body;
        
        public CAlLogin() {
        }
        
        public CAlLogin(JHDock.JHIPSSO.CAlLoginBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class CAlLoginBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string inputPara;
        
        public CAlLoginBody() {
        }
        
        public CAlLoginBody(string inputPara) {
            this.inputPara = inputPara;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CAlLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CAlLoginResponse", Namespace="http://jhipwebsvc.bjgoodwill.com/", Order=0)]
        public JHDock.JHIPSSO.CAlLoginResponseBody Body;
        
        public CAlLoginResponse() {
        }
        
        public CAlLoginResponse(JHDock.JHIPSSO.CAlLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://jhipwebsvc.bjgoodwill.com/")]
    public partial class CAlLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string returnVal;
        
        public CAlLoginResponseBody() {
        }
        
        public CAlLoginResponseBody(string returnVal) {
            this.returnVal = returnVal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserDetailInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserDetailInfo", Namespace="http://jhipwebsvc.bjgoodwill.com/", Order=0)]
        public JHDock.JHIPSSO.getUserDetailInfoBody Body;
        
        public getUserDetailInfo() {
        }
        
        public getUserDetailInfo(JHDock.JHIPSSO.getUserDetailInfoBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getUserDetailInfoBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string inputPara;
        
        public getUserDetailInfoBody() {
        }
        
        public getUserDetailInfoBody(string inputPara) {
            this.inputPara = inputPara;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserDetailInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserDetailInfoResponse", Namespace="http://jhipwebsvc.bjgoodwill.com/", Order=0)]
        public JHDock.JHIPSSO.getUserDetailInfoResponseBody Body;
        
        public getUserDetailInfoResponse() {
        }
        
        public getUserDetailInfoResponse(JHDock.JHIPSSO.getUserDetailInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://jhipwebsvc.bjgoodwill.com/")]
    public partial class getUserDetailInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string returnVal;
        
        public getUserDetailInfoResponseBody() {
        }
        
        public getUserDetailInfoResponseBody(string returnVal) {
            this.returnVal = returnVal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNewSessionID {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getNewSessionID", Namespace="http://jhipwebsvc.bjgoodwill.com/", Order=0)]
        public JHDock.JHIPSSO.getNewSessionIDBody Body;
        
        public getNewSessionID() {
        }
        
        public getNewSessionID(JHDock.JHIPSSO.getNewSessionIDBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getNewSessionIDBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string inputPara;
        
        public getNewSessionIDBody() {
        }
        
        public getNewSessionIDBody(string inputPara) {
            this.inputPara = inputPara;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNewSessionIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getNewSessionIDResponse", Namespace="http://jhipwebsvc.bjgoodwill.com/", Order=0)]
        public JHDock.JHIPSSO.getNewSessionIDResponseBody Body;
        
        public getNewSessionIDResponse() {
        }
        
        public getNewSessionIDResponse(JHDock.JHIPSSO.getNewSessionIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://jhipwebsvc.bjgoodwill.com/")]
    public partial class getNewSessionIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string returnVal;
        
        public getNewSessionIDResponseBody() {
        }
        
        public getNewSessionIDResponseBody(string returnVal) {
            this.returnVal = returnVal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModifyPassword {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModifyPassword", Namespace="http://jhipwebsvc.bjgoodwill.com/", Order=0)]
        public JHDock.JHIPSSO.ModifyPasswordBody Body;
        
        public ModifyPassword() {
        }
        
        public ModifyPassword(JHDock.JHIPSSO.ModifyPasswordBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ModifyPasswordBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string inputPara;
        
        public ModifyPasswordBody() {
        }
        
        public ModifyPasswordBody(string inputPara) {
            this.inputPara = inputPara;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModifyPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModifyPasswordResponse", Namespace="http://jhipwebsvc.bjgoodwill.com/", Order=0)]
        public JHDock.JHIPSSO.ModifyPasswordResponseBody Body;
        
        public ModifyPasswordResponse() {
        }
        
        public ModifyPasswordResponse(JHDock.JHIPSSO.ModifyPasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://jhipwebsvc.bjgoodwill.com/")]
    public partial class ModifyPasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string returnVal;
        
        public ModifyPasswordResponseBody() {
        }
        
        public ModifyPasswordResponseBody(string returnVal) {
            this.returnVal = returnVal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadSystemDetail {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadSystemDetail", Namespace="http://jhipwebsvc.bjgoodwill.com/", Order=0)]
        public JHDock.JHIPSSO.LoadSystemDetailBody Body;
        
        public LoadSystemDetail() {
        }
        
        public LoadSystemDetail(JHDock.JHIPSSO.LoadSystemDetailBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class LoadSystemDetailBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string inputPara;
        
        public LoadSystemDetailBody() {
        }
        
        public LoadSystemDetailBody(string inputPara) {
            this.inputPara = inputPara;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadSystemDetailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadSystemDetailResponse", Namespace="http://jhipwebsvc.bjgoodwill.com/", Order=0)]
        public JHDock.JHIPSSO.LoadSystemDetailResponseBody Body;
        
        public LoadSystemDetailResponse() {
        }
        
        public LoadSystemDetailResponse(JHDock.JHIPSSO.LoadSystemDetailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://jhipwebsvc.bjgoodwill.com/")]
    public partial class LoadSystemDetailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string returnVal;
        
        public LoadSystemDetailResponseBody() {
        }
        
        public LoadSystemDetailResponseBody(string returnVal) {
            this.returnVal = returnVal;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SsoWebsvcChannel : JHDock.JHIPSSO.SsoWebsvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SsoWebsvcClient : System.ServiceModel.ClientBase<JHDock.JHIPSSO.SsoWebsvc>, JHDock.JHIPSSO.SsoWebsvc {
        
        public SsoWebsvcClient() {
        }
        
        public SsoWebsvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SsoWebsvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SsoWebsvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SsoWebsvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JHDock.JHIPSSO.LoadAllSystemResponse JHDock.JHIPSSO.SsoWebsvc.LoadAllSystem(JHDock.JHIPSSO.LoadAllSystem request) {
            return base.Channel.LoadAllSystem(request);
        }
        
        public string LoadAllSystem(string inputPara) {
            JHDock.JHIPSSO.LoadAllSystem inValue = new JHDock.JHIPSSO.LoadAllSystem();
            inValue.Body = new JHDock.JHIPSSO.LoadAllSystemBody();
            inValue.Body.inputPara = inputPara;
            JHDock.JHIPSSO.LoadAllSystemResponse retVal = ((JHDock.JHIPSSO.SsoWebsvc)(this)).LoadAllSystem(inValue);
            return retVal.Body.returnVal;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JHDock.JHIPSSO.LoadSystemFileResponse JHDock.JHIPSSO.SsoWebsvc.LoadSystemFile(JHDock.JHIPSSO.LoadSystemFile request) {
            return base.Channel.LoadSystemFile(request);
        }
        
        public string LoadSystemFile(string inputPara) {
            JHDock.JHIPSSO.LoadSystemFile inValue = new JHDock.JHIPSSO.LoadSystemFile();
            inValue.Body = new JHDock.JHIPSSO.LoadSystemFileBody();
            inValue.Body.inputPara = inputPara;
            JHDock.JHIPSSO.LoadSystemFileResponse retVal = ((JHDock.JHIPSSO.SsoWebsvc)(this)).LoadSystemFile(inValue);
            return retVal.Body.returnVal;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JHDock.JHIPSSO.LogInResponse JHDock.JHIPSSO.SsoWebsvc.LogIn(JHDock.JHIPSSO.LogIn request) {
            return base.Channel.LogIn(request);
        }
        
        public string LogIn(string inputPara) {
            JHDock.JHIPSSO.LogIn inValue = new JHDock.JHIPSSO.LogIn();
            inValue.Body = new JHDock.JHIPSSO.LogInBody();
            inValue.Body.inputPara = inputPara;
            JHDock.JHIPSSO.LogInResponse retVal = ((JHDock.JHIPSSO.SsoWebsvc)(this)).LogIn(inValue);
            return retVal.Body.returnVal;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JHDock.JHIPSSO.CAlLoginResponse JHDock.JHIPSSO.SsoWebsvc.CAlLogin(JHDock.JHIPSSO.CAlLogin request) {
            return base.Channel.CAlLogin(request);
        }
        
        public string CAlLogin(string inputPara) {
            JHDock.JHIPSSO.CAlLogin inValue = new JHDock.JHIPSSO.CAlLogin();
            inValue.Body = new JHDock.JHIPSSO.CAlLoginBody();
            inValue.Body.inputPara = inputPara;
            JHDock.JHIPSSO.CAlLoginResponse retVal = ((JHDock.JHIPSSO.SsoWebsvc)(this)).CAlLogin(inValue);
            return retVal.Body.returnVal;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JHDock.JHIPSSO.getUserDetailInfoResponse JHDock.JHIPSSO.SsoWebsvc.getUserDetailInfo(JHDock.JHIPSSO.getUserDetailInfo request) {
            return base.Channel.getUserDetailInfo(request);
        }
        
        public string getUserDetailInfo(string inputPara) {
            JHDock.JHIPSSO.getUserDetailInfo inValue = new JHDock.JHIPSSO.getUserDetailInfo();
            inValue.Body = new JHDock.JHIPSSO.getUserDetailInfoBody();
            inValue.Body.inputPara = inputPara;
            JHDock.JHIPSSO.getUserDetailInfoResponse retVal = ((JHDock.JHIPSSO.SsoWebsvc)(this)).getUserDetailInfo(inValue);
            return retVal.Body.returnVal;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JHDock.JHIPSSO.getNewSessionIDResponse JHDock.JHIPSSO.SsoWebsvc.getNewSessionID(JHDock.JHIPSSO.getNewSessionID request) {
            return base.Channel.getNewSessionID(request);
        }
        
        public string getNewSessionID(string inputPara) {
            JHDock.JHIPSSO.getNewSessionID inValue = new JHDock.JHIPSSO.getNewSessionID();
            inValue.Body = new JHDock.JHIPSSO.getNewSessionIDBody();
            inValue.Body.inputPara = inputPara;
            JHDock.JHIPSSO.getNewSessionIDResponse retVal = ((JHDock.JHIPSSO.SsoWebsvc)(this)).getNewSessionID(inValue);
            return retVal.Body.returnVal;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JHDock.JHIPSSO.ModifyPasswordResponse JHDock.JHIPSSO.SsoWebsvc.ModifyPassword(JHDock.JHIPSSO.ModifyPassword request) {
            return base.Channel.ModifyPassword(request);
        }
        
        public string ModifyPassword(string inputPara) {
            JHDock.JHIPSSO.ModifyPassword inValue = new JHDock.JHIPSSO.ModifyPassword();
            inValue.Body = new JHDock.JHIPSSO.ModifyPasswordBody();
            inValue.Body.inputPara = inputPara;
            JHDock.JHIPSSO.ModifyPasswordResponse retVal = ((JHDock.JHIPSSO.SsoWebsvc)(this)).ModifyPassword(inValue);
            return retVal.Body.returnVal;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JHDock.JHIPSSO.LoadSystemDetailResponse JHDock.JHIPSSO.SsoWebsvc.LoadSystemDetail(JHDock.JHIPSSO.LoadSystemDetail request) {
            return base.Channel.LoadSystemDetail(request);
        }
        
        public string LoadSystemDetail(string inputPara) {
            JHDock.JHIPSSO.LoadSystemDetail inValue = new JHDock.JHIPSSO.LoadSystemDetail();
            inValue.Body = new JHDock.JHIPSSO.LoadSystemDetailBody();
            inValue.Body.inputPara = inputPara;
            JHDock.JHIPSSO.LoadSystemDetailResponse retVal = ((JHDock.JHIPSSO.SsoWebsvc)(this)).LoadSystemDetail(inValue);
            return retVal.Body.returnVal;
        }
    }
}
